name: Docker Image CI

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set Image tag
      run: |
          echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/sandorkevin/webtest4azure:$IMAGE_TAG --tag ghcr.io/sandorkevin/webtest4azure:latest
        docker login ghcr.io -u sandorkevin -p ${{secrets.GHCR_TOKEN}}
        docker push ghcr.io/sandorkevin/webtest4azure:$IMAGE_TAG
        docker push ghcr.io/sandorkevin/webtest4azure:latest
        
